name: GHAction zad2

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, scan, and push Docker image to DockerHub
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      - 
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/my-app
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/my-app:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/my-app:cache ,mode=max  
          tags: ${{ steps.meta.outputs.tags }}
      
      - 
        name: Docker Scout scan for vulnerabilities
        id: scout-scan
        run: |
          docker scout quickview ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest \
            --format json > scout-report.json
          CRITICAL_COUNT=$(jq '.summary.critical' scout-report.json)
          HIGH_COUNT=$(jq '.summary.high' scout-report.json)
          if [ "$CRITICAL_COUNT" -gt 0 ] || [ "$HIGH_COUNT" -gt 0 ]; then
            echo "Found critical or high vulnerabilities."
            echo "::error file=scout-report.json::Scan failed with $CRITICAL_COUNT critical and $HIGH_COUNT high vulnerabilities."
            exit 1
          else
            echo "No critical or high vulnerabilities found."
          fi
      
      - 
        name: Push Docker image to DockerHub
        if: success() 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/my-app:cache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/my-app:cache,mode=max  
          tags: ${{ steps.meta.outputs.tags }}
